name: Unit Tests

on:
  push:
    branches:
      - main

jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: Download Go Modules
        working-directory: tests
        run: go mod download

#      - name: Security Scan
#        id: Bridgecrew
#        uses: bridgecrewio/bridgecrew-action@master
#        with:
#          api-key: ${{ secrets.BRIDGECREW_API_KEY }}

      - name: Run Go Tests
        working-directory: tests
        run: |
          go test -v
        env:
          # TF ENVIRONMENT
          TF_GCLOUD_BUCKET: "${{ secrets.GCP_NONPROD_BUCKET }}"
          TF_GCLOUD_PREFIX: "${{ secrets.GCP_PREFIX }}"
          TF_GCLOUD_CREDENTIALS: "${{ secrets.NONPROD_CREDENTIALS }}"